In [6]:
#import all dependencies
%matplotlib inline
from IPython.display import Image
import import_ipynb
import plotly
from  plotly import plotly as py
plotly.tools.set_credentials_file(username='arinmuk', api_key='UrLqynaS1XJWLX0mgx6V')
import pandas as pd
import gmaps
# Dependencies and Setup
import matplotlib.pyplot as plt
import numpy as np
import time
import datetime
from datetime import date
from plotly import tools
from pandas.tools.plotting import table
from utils.config import gkey
from cleanup_allfunctions import data_cleanup
from cleanup_allfunctions import buildmapbystatevio
from cleanup_allfunctions import gun_vio_locations
from cleanup_allfunctions import casualties_by_qtr_yr
from cleanup_allfunctions import gun_ownership_crime_report
from cleanup_allfunctions import build_victims_kil_stackedbar_state_year
from cleanup_allfunctions import build_victims_inj_stackedbar_state_year
from cleanup_allfunctions import casualty_plot
from cleanup_allfunctions import read_create_df_st_bars
from cleanup_allfunctions import setread_csvfile

In [7]:
yr = input("Gun Violations State - Please enter the year ")
usa_gunviobyyr_df=setread_csvfile(yr,True)
usa_gunviobyyr_df.head(52)

Gun Violations State - Please enter the year 2017

    Year                 state  KilledCount  InjuredCount
0   2017               Alabama          544           856
1   2017                Alaska           69            70
2   2017               Arizona          289           298
3   2017              Arkansas          216           437
4   2017            California         1423          1953
5   2017              Colorado          199           300
6   2017           Connecticut           89           293
7   2017              Delaware           56           241
8   2017  District of Columbia          100           340
9   2017               Florida          950          1801
10  2017               Georgia          658          1057
11  2017                Hawaii            8            20
12  2017                 Idaho           47            34
13  2017              Illinois          959          3629
14  2017               Indiana          407           737
15  2017                  Iowa           71           229
16  2017                Kansas          152           264
17  2017              Kentucky          273           518
18  2017             Louisiana          549          1184
19  2017                 Maine           33            36
20  2017              Maryland          480           855
21  2017         Massachusetts          128           456
22  2017              Michigan          369           771
23  2017             Minnesota          115           282
24  2017           Mississippi          324           593
25  2017              Missouri          609           921
26  2017               Montana           41            33
27  2017              Nebraska           47           152
28  2017                Nevada          200           218
29  2017         New Hampshire           23            30
30  2017            New Jersey          275           663
31  2017            New Mexico          125           141
32  2017              New York          347          1092
33  2017        North Carolina          556          1153
34  2017          North Dakota           15            33
35  2017                  Ohio          700          1517
36  2017              Oklahoma          249           384
37  2017                Oregon           99           170
38  2017          Pennsylvania          635          1188
39  2017          Rhode Island           11            79
40  2017        South Carolina          395           791
41  2017          South Dakota           19            21
42  2017             Tennessee          495          1198
43  2017                 Texas         1169          1565
44  2017                  Utah           70           110
45  2017               Vermont            9            11
46  2017              Virginia          385           939
47  2017            Washington          230           352
48  2017         West Virginia           81           156
49  2017             Wisconsin          209           519
50  2017               Wyoming            9            13

In [8]:
#mapfig=buildmapbystatevio(usa_gunviobyyr_df,yr)
#py.iplot( mapfig, filename='d3-cloropleth-map' )



#def buildmapbystatevio(cities_pd,yr):
cities_pd=usa_gunviobyyr_df

us_state_abbrev = {
            'Alabama': 'AL',
            'Alaska': 'AK',
            'Arizona': 'AZ',
            'Arkansas': 'AR',
            'California': 'CA',
            'Colorado': 'CO',
            'Connecticut': 'CT',
            'Delaware': 'DE',
            'Florida': 'FL',
            'Georgia': 'GA',
            'Hawaii': 'HI',
            'Idaho': 'ID',
            'Illinois': 'IL',
            'Indiana': 'IN',
            'Iowa': 'IA',
            'Kansas': 'KS',
            'Kentucky': 'KY',
            'Louisiana': 'LA',
            'Maine': 'ME',
            'Maryland': 'MD',
            'Massachusetts': 'MA',
            'Michigan': 'MI',
            'Minnesota': 'MN',
            'Mississippi': 'MS',
            'Missouri': 'MO',
            'Montana': 'MT',
            'Nebraska': 'NE',
            'Nevada': 'NV',
            'New Hampshire': 'NH',
            'New Jersey': 'NJ',
            'New Mexico': 'NM',
            'New York': 'NY',
            'North Carolina': 'NC',
            'North Dakota': 'ND',
            'Ohio': 'OH',
            'Oklahoma': 'OK',
            'Oregon': 'OR',
            'Pennsylvania': 'PA',
            'Rhode Island': 'RI',
            'South Carolina': 'SC',
            'South Dakota': 'SD',
            'Tennessee': 'TN',
            'Texas': 'TX',
            'Utah': 'UT',
            'Vermont': 'VT',
            'Virginia': 'VA',
            'Washington': 'WA',
            'West Virginia': 'WV',
            'Wisconsin': 'WI',
            'Wyoming': 'WY',
        }
  
cities_pd['code'] = cities_pd['state'].map(us_state_abbrev)

for col in cities_pd.columns:
            cities_pd[col] = cities_pd[col].astype(str)

cities_pd['text'] = cities_pd['state'] + '<br>' +\
            'Total Killed '+cities_pd['KilledCount']+ '<br>' + 'Total Injured '+cities_pd['InjuredCount']

data = [ dict(
                type='choropleth',
                autocolorscale = True,
                locations = cities_pd["code"],
                z = cities_pd['KilledCount'].astype(float)+cities_pd['InjuredCount'].astype(float),
                locationmode = 'USA-states',
                text = cities_pd['text'],
                marker = dict(
                    line = dict (
                        color = 'rgb(255,255,255)',
                        width = 2
                    ) ),
                colorbar = dict(
                    title = "Killed in Numbers")
                ) ]
layout = dict(
                title=f"Gun Violations by  State<br>(Hover for breakdown) {yr}",
                geo = dict(
                    scope='usa',
                    projection=dict( type='albers usa' ),
                    showlakes = True,
                    lakecolor = 'rgb(255, 255, 255)'),
                     )

fig = dict( data=data, layout=layout )
py.iplot( fig, filename='d3-cloropleth-map' )
        #return fig

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~arinmuk/0 or inside your plot.ly account where it is named 'd3-cloropleth-map'

C:\Users\arin_\AppData\Local\conda\conda\envs\Pythondata\lib\site-packages\IPython\core\display.py:689: UserWarning:

Consider using IPython.display.IFrame instead