In [5]:
#import all dependencies
%matplotlib inline
from IPython.display import Image
import import_ipynb
import plotly
from  plotly import plotly as py
plotly.tools.set_credentials_file(username='arinmuk', api_key='UrLqynaS1XJWLX0mgx6V')
import pandas as pd
import gmaps
import gmaps.datasets
# Dependencies and Setup
import matplotlib.pyplot as plt
import numpy as np
import time
import datetime
from datetime import date
from plotly import tools
from pandas.tools.plotting import table
from utils.config import gkey
gmaps.configure(api_key=gkey)
from cleanup_allfunctions import data_cleanup
from cleanup_allfunctions import buildmapbystatevio
from cleanup_allfunctions import gun_vio_locations
from cleanup_allfunctions import casualties_by_qtr_yr
from cleanup_allfunctions import gun_ownership_crime_report
from cleanup_allfunctions import build_victims_kil_stackedbar_state_year
from cleanup_allfunctions import build_victims_inj_stackedbar_state_year
from cleanup_allfunctions import casualty_plot
from cleanup_allfunctions import read_create_df_st_bars
from cleanup_allfunctions import setread_csvfile

In [6]:
yr = input("Gun Violations State - Please enter the year ")
usa_gunviobyyr_df=setread_csvfile(yr,True)
usa_gunviobyyr_df.head(52)

Gun Violations State - Please enter the year 2018

    Year                 state  KilledCount  InjuredCount
0   2018               Alabama          135           219
1   2018                Alaska           11            19
2   2018               Arizona           85            73
3   2018              Arkansas           43            83
4   2018            California          304           432
5   2018              Colorado           61            79
6   2018           Connecticut           17            57
7   2018              Delaware            8            28
8   2018  District of Columbia           25            61
9   2018               Florida          267           379
10  2018               Georgia          128           203
11  2018                Hawaii            1             8
12  2018                 Idaho           14             9
13  2018              Illinois          165           572
14  2018               Indiana           96           131
15  2018                  Iowa           10            36
16  2018                Kansas           38            55
17  2018              Kentucky           77           125
18  2018             Louisiana          129           240
19  2018                 Maine            8             3
20  2018              Maryland           79           163
21  2018         Massachusetts           22            80
22  2018              Michigan          122           188
23  2018             Minnesota           26            64
24  2018           Mississippi          106           136
25  2018              Missouri          128           215
26  2018               Montana            5            13
27  2018              Nebraska           11            31
28  2018                Nevada           61            56
29  2018         New Hampshire            1            10
30  2018            New Jersey           57            72
31  2018            New Mexico           37            24
32  2018              New York           67           150
33  2018        North Carolina          108           244
34  2018          North Dakota            3             7
35  2018                  Ohio          139           277
36  2018              Oklahoma           44            92
37  2018                Oregon           31            39
38  2018          Pennsylvania          136           238
39  2018          Rhode Island            5            13
40  2018        South Carolina           89           192
41  2018          South Dakota            7            13
42  2018             Tennessee           98           210
43  2018                 Texas          310           374
44  2018                  Utah           10            33
45  2018               Vermont            4             3
46  2018              Virginia           72           187
47  2018            Washington           54            83
48  2018         West Virginia           23            34
49  2018             Wisconsin           46           118

In [7]:
#build google map with lat and lng where casualities happened
usa_gunviobyyr_df=setread_csvfile(yr,False)
testfr=usa_gunviobyyr_df.head(5)
geomaps=gun_vio_locations(testfr,gkey)
fig = gmaps.figure()
fig.add_layer(geomaps)
print("gmaps build completed...............")
fig

cleanup_allfunctions.ipynb:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

cleanup_allfunctions.ipynb:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\arin_\AppData\Local\conda\conda\envs\Pythondata\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

gmaps build completed...............

Figure(layout=FigureLayout(height='420px'))

In [8]:
#mapfig=buildmapbystatevio(usa_gunviobyyr_df,yr)
#py.iplot( mapfig, filename='d3-cloropleth-map' )



#def buildmapbystatevio(cities_pd,yr):
cities_pd=usa_gunviobyyr_df

us_state_abbrev = {
            'Alabama': 'AL',
            'Alaska': 'AK',
            'Arizona': 'AZ',
            'Arkansas': 'AR',
            'California': 'CA',
            'Colorado': 'CO',
            'Connecticut': 'CT',
            'Delaware': 'DE',
            'Florida': 'FL',
            'Georgia': 'GA',
            'Hawaii': 'HI',
            'Idaho': 'ID',
            'Illinois': 'IL',
            'Indiana': 'IN',
            'Iowa': 'IA',
            'Kansas': 'KS',
            'Kentucky': 'KY',
            'Louisiana': 'LA',
            'Maine': 'ME',
            'Maryland': 'MD',
            'Massachusetts': 'MA',
            'Michigan': 'MI',
            'Minnesota': 'MN',
            'Mississippi': 'MS',
            'Missouri': 'MO',
            'Montana': 'MT',
            'Nebraska': 'NE',
            'Nevada': 'NV',
            'New Hampshire': 'NH',
            'New Jersey': 'NJ',
            'New Mexico': 'NM',
            'New York': 'NY',
            'North Carolina': 'NC',
            'North Dakota': 'ND',
            'Ohio': 'OH',
            'Oklahoma': 'OK',
            'Oregon': 'OR',
            'Pennsylvania': 'PA',
            'Rhode Island': 'RI',
            'South Carolina': 'SC',
            'South Dakota': 'SD',
            'Tennessee': 'TN',
            'Texas': 'TX',
            'Utah': 'UT',
            'Vermont': 'VT',
            'Virginia': 'VA',
            'Washington': 'WA',
            'West Virginia': 'WV',
            'Wisconsin': 'WI',
            'Wyoming': 'WY',
        }
  
cities_pd['code'] = cities_pd['state'].map(us_state_abbrev)

for col in cities_pd.columns:
            cities_pd[col] = cities_pd[col].astype(str)

cities_pd['text'] = cities_pd['state'] + '<br>' +\
            'Total Killed '+cities_pd['KilledCount']+ '<br>' + 'Total Injured '+cities_pd['InjuredCount']

data = [ dict(
                type='choropleth',
                autocolorscale = True,
                locations = cities_pd["code"],
                z = cities_pd['KilledCount'].astype(float)+cities_pd['InjuredCount'].astype(float),
                locationmode = 'USA-states',
                text = cities_pd['text'],
                marker = dict(
                    line = dict (
                        color = 'rgb(255,255,255)',
                        width = 2
                    ) ),
                colorbar = dict(
                    title = "Killed in Numbers")
                ) ]
layout = dict(
                title=f"Gun Violations by  State<br>(Hover for breakdown) {yr}",
                geo = dict(
                    scope='usa',
                    projection=dict( type='albers usa' ),
                    showlakes = True,
                    lakecolor = 'rgb(255, 255, 255)'),
                     )

fig = dict( data=data, layout=layout )
py.iplot( fig, filename='d3-cloropleth-map' )
        #return fig

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~arinmuk/0 or inside your plot.ly account where it is named 'd3-cloropleth-map'

C:\Users\arin_\AppData\Local\conda\conda\envs\Pythondata\lib\site-packages\IPython\core\display.py:689: UserWarning:

Consider using IPython.display.IFrame instead